// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

com.mgn.ai.data.model.Conversation
com.mgn.ai.data.model.MessageNode
com.mgn.ai.ai.ui.UIMessage
com.mgn.ai.ai.ui.UIMessageChoice
com.mgn.ai.ai.ui.MessageChunk
com.mgn.ai.ai.ui.UIMessageAnnotation
com.mgn.ai.ai.ui.ToolApprovalState
com.mgn.ai.ai.core.TokenUsage